version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    container_name: laravel-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    container_name: angular-frontend
    ports:
      - "4200:80"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
