services:
  backend:
    image: nouha564/laravel-backend:v1
    container_name: laravel-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      - webapp

  frontend:
    image: nouha564/angular-frontend:v1
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - webapp

  mysql:
    image: nouha564/mysql-custom:v1
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - webapp

volumes:
  dbdata:

networks:
  webapp:
    driver: bridge
