# Étape 1 : Utiliser une image de base officielle avec PHP, Apache et Composer
FROM php:8.3-apache

# Étape 2 : Installer les extensions PHP nécessaires à Laravel
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    curl \
    && docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl xml

# Étape 3 : Activer le module Apache rewrite (important pour Laravel)
RUN a2enmod rewrite

# Étape 4 : Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Étape 5 : Copier le projet Laravel dans le conteneur
COPY ./backend /var/www/html

# Étape 6 : Définir le répertoire de travail
WORKDIR /var/www/html

# Étape 7 : Donner les bonnes permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Étape 8 : Installer les dépendances Laravel avec Composer
RUN composer install

# Étape 9 : Exposer le port 80
EXPOSE 80
