# Étape 1 : Utilise une image officielle de Node.js pour builder Angular
FROM node:20-alpine AS build

# Étape 2 : Répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers de ton projet Angular
COPY ./frontend /app

# Étape 4 : Installer les dépendances et builder l'app Angular
RUN npm install && npm run build --configuration=production

# Étape 5 : Utilise NGINX pour servir l’app Angular
FROM nginx:stable-alpine

# Étape 6 : Copier les fichiers générés dans le dossier NGINX
COPY --from=build /app/dist/* /usr/share/nginx/html

# Étape 7 : Expose le port 80
EXPOSE 80
